apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nq6unwwxj-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nq6unwwxj-java-springboot-gitops